services:
  dsquares:
    container_name: dsquares-${tag:-latest}
    image: dsquares-${tag:-latest}
    build:
      context: .
      args:
        DOCKER_BUILDKIT: 1
        GIT_CREDENTIALS: $GIT_CREDENTIALS
    working_dir: /usr/src/app
    environment:
      PORT: 3003
      DEBUG1: "*,-morgan,-agentkeepalive,-send,-body-parser:*,-nodemon*,-express:*,-mongooose-jsproxy,-ezsso:express-client:*"
      DEBUG: "*"
    restart: always
    ports:
      - '3003/tcp'
    volumes:
      - ${PWD}/secrets/.env.local:/usr/src/app/.env.local
      - ${DPSRV_HOME}/rc/secrets/mongo/conf/:/etc/mongo/:ro
      - ${DPSRV_HOME}/rc/secrets/cloud-gcp/:/usr/src/app/.config/gcloud/:ro
    command: [ "npm", "start" ]
networks:
  default:
    name: dpsrv
    external: true
